/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicGuessRouteImport } from './routes/api/public/guess'
import { Route as ApiPublicLocationsRouteImport } from './routes/api/public/locations'
import { Route as ApiPublicTreeRouteImport } from './routes/api/public/tree'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGuessRoute = ApiPublicGuessRouteImport.update({
  id: '/api/public/guess',
  path: '/api/public/guess',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLocationsRoute = ApiPublicLocationsRouteImport.update({
  id: '/api/public/locations',
  path: '/api/public/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTreeRoute = ApiPublicTreeRouteImport.update({
  id: '/api/public/tree',
  path: '/api/public/tree',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/guess': typeof ApiPublicGuessRoute
  '/api/public/locations': typeof ApiPublicLocationsRoute
  '/api/public/tree': typeof ApiPublicTreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/guess': typeof ApiPublicGuessRoute
  '/api/public/locations': typeof ApiPublicLocationsRoute
  '/api/public/tree': typeof ApiPublicTreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/guess': typeof ApiPublicGuessRoute
  '/api/public/locations': typeof ApiPublicLocationsRoute
  '/api/public/tree': typeof ApiPublicTreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/public/guess' | '/api/public/locations' | '/api/public/tree'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/guess' | '/api/public/locations' | '/api/public/tree'
  id:
    | '__root__'
    | '/'
    | '/api/public/guess'
    | '/api/public/locations'
    | '/api/public/tree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicGuessRoute: typeof ApiPublicGuessRoute
  ApiPublicLocationsRoute: typeof ApiPublicLocationsRoute
  ApiPublicTreeRoute: typeof ApiPublicTreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guess': {
      id: '/api/public/guess'
      path: '/api/public/guess'
      fullPath: '/api/public/guess'
      preLoaderRoute: typeof ApiPublicGuessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/locations': {
      id: '/api/public/locations'
      path: '/api/public/locations'
      fullPath: '/api/public/locations'
      preLoaderRoute: typeof ApiPublicLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tree': {
      id: '/api/public/tree'
      path: '/api/public/tree'
      fullPath: '/api/public/tree'
      preLoaderRoute: typeof ApiPublicTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicGuessRoute: ApiPublicGuessRoute,
  ApiPublicLocationsRoute: ApiPublicLocationsRoute,
  ApiPublicTreeRoute: ApiPublicTreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
